config/routes.rb
Rails.application.routes.draw do
  root 'leagues#index'

  resources :leagues
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/league.rb
class League < ApplicationRecord
  validates :name, :year, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]
  def index

  end

  def new
    @league = League.new
  end

  def create
    @league = League.new(league_params)
    if @league.save
      flash[:success] = "#{@league.name} #{@league.year} has been created."
      redirect_to league_path(@league)
    else
      flash.now[:danger] = "League creation failed."
      render 'new'
    end
  end

  def show
  end

  def edit
    
  end

  def update
    if @league.update_attributes(league_params)
      flash[:success] = "Your league has been updated."
      redirect_to league_path(@league)
    else
      flash.now[:danger] = "League update failed."
      render 'edit'
    end
  end

  def destroy
    @league.destroy
    flash[:success] = "Your league has been deleted"
    redirect_to new_league_path
  end

  private

    def league_params
      params.require(:league).permit(:name, :year, :champion)
    end

    def set_league
      @league = League.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Baseball</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md">
      <%= link_to "SOM Baseball App", root_url, :class => "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Home", "#", :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Games", "#", :class => 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container-fluid">
      <% flash.each do |msg_type, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{msg_type}") %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/leagues/_form.html.erb
<div class="row">
  <div class="col-12 col-md-2 offset-md-5 text-center">
    <%= form_for @league do |f| %>

      <%= f.label :name, "League Name", class: "form-label mt-3" %>
      <%= f.text_field :name, class: 'form-control text-center' %>

      <%= f.label :year, "League Year", class: 'form-label mt-3' %>
      <%= f.number_field :year, class: 'form-control text-center', value: 2018 %>

      <%= f.submit "Submit", class: 'btn btn-info btn-block mt-3' %>
    <% end %>
  </div>
</div>

app/views/leagues/edit.html.erb
    <%= render 'form' %>

app/views/leagues/new.html.erb
<%= render 'form' %>

app/views/leagues/show.html.erb
<div class="row">
  <div class="col-12 col-md-4 offset-md-4">
    <h1 class="text-center"><%= @league.name %></h1>
    <p class="text-center"><%= @league.year %></p>
  </div>
</div>
<div class="row">
  <div class="col-12 col-md-4 offset-md-4">
    <p class="text-center edit-link">
      <%= link_to "edit", edit_league_path(@league), class: 'btn btn-outline-info btn-sm mt-3' %><br>
      <%= link_to 'delete', @league, method: :delete, data: {confirm: "Delete this league?" }, class: 'btn btn-outline-danger btn-sm mt-3' %>
    </p>
  </div>
</div>